FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY pom.xml .
COPY src src
RUN mvn -B -DskipTests --no-transfer-progress package

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /workspace/target/crimewatch-api.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

