import { useEffect, useState } from 'react'
import { Activity, CheckCircle2, Database, HardDrive, Server, ShieldCheck, UserRound, Users } from 'lucide-react'
import { api, formatDate, formatStatus } from '../api'
import { Alert, Loader, PageHeader, StatusBadge } from '../components/Ui'

export function UsersPage(){const[users,setUsers]=useState(null);useEffect(()=>{api('/admin/users').then(setUsers)},[]);if(!users)return <Loader/>;const counts=role=>users.filter(u=>u.role===role).length;return <><PageHeader eyebrow="Identity administration" title="Users & officers" subtitle="Review the identities and roles authorized in this CrimeWatch environment."/><div className="metrics-grid compact"><Mini icon={Users} label="All users" value={users.length}/><Mini icon={UserRound} label="Citizens" value={counts('CITIZEN')}/><Mini icon={ShieldCheck} label="Officers" value={counts('OFFICER')}/><Mini icon={Activity} label="Administrators" value={counts('ADMIN')}/></div><section className="panel"><div className="panel-head"><div><span className="eyebrow">Account directory</span><h2>Registered identities</h2></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Phone</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.fullName}</b></td><td>{u.email}</td><td><span className={`role-label role-${u.role.toLowerCase()}`}>{formatStatus(u.role)}</span></td><td>{u.phone||'—'}</td></tr>)}</tbody></table></div></section></>}
export function AuditPage(){const[data,setData]=useState(null);useEffect(()=>{api('/audit?limit=100').then(setData)},[]);if(!data)return <Loader/>;return <><PageHeader eyebrow="Accountability" title="System audit trail" subtitle="A timestamped record of important authentication and case-management events."/><section className="panel audit-list"><div className="panel-head"><div><span className="eyebrow">Latest activity</span><h2>{data.length} recorded events</h2></div></div>{data.map(a=><article key={a.id}><span><Activity/></span><div><b>{formatStatus(a.action)} <small>{a.entityType} · {a.entityId}</small></b><p>{a.details}</p><em>{a.actor} · {formatDate(a.createdAt)}</em></div></article>)}</section></>}
export function SystemPage(){const[health,setHealth]=useState(null),[error,setError]=useState('');useEffect(()=>{fetch('/actuator/health').then(r=>r.json()).then(setHealth).catch(e=>setError(e.message))},[]);return <><PageHeader eyebrow="Deployment visibility" title="System information" subtitle="Runtime health and DevOps architecture for this CrimeWatch deployment."/>{error&&<Alert>{error}</Alert>}<div className="system-grid"><section className="panel health-card"><span className={`health-orb ${health?.status==='UP'?'up':''}`}><CheckCircle2/></span><div><span className="eyebrow">Backend health</span><h2>{health?.status||'Checking…'}</h2><p>Spring Boot actuator health endpoint</p></div></section><SystemCard icon={Database} title="PostgreSQL" text="Persistent relational data store"/><SystemCard icon={Server} title="Spring Boot API" text="Java 17 · Port 8080"/><SystemCard icon={HardDrive} title="Docker volume" text="Persistent database storage"/></div><section className="panel architecture-panel"><span className="eyebrow">Integrated delivery path</span><h2>DevOps deployment architecture</h2><div className="architecture-flow">{['GitHub','Jenkins','Build & Test','Docker Images','Ansible','Nginx + Application'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b>{i<5&&<i>→</i>}</div>)}</div><p>Each delivery must pass automated tests before image creation and deployment. External webhook execution is documented separately and must be verified against the configured GitHub repository.</p></section></>}
function Mini({icon:Icon,label,value}){return <div className="mini-metric"><Icon/><span><small>{label}</small><b>{value}</b></span></div>}
function SystemCard({icon:Icon,title,text}){return <section className="panel system-card"><Icon/><div><h3>{title}</h3><p>{text}</p></div></section>}
