import { useEffect, useState } from 'react'
import { Activity, CheckCircle2, ClipboardList, MapPin, ShieldAlert } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api'
import { Alert, Loader, MetricCard, PageHeader } from '../components/Ui'

const colors=['#1d4ed8','#0ea5e9','#8b5cf6','#f59e0b','#10b981','#64748b','#ef4444','#14b8a6','#f97316','#6366f1']
export default function Analytics(){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/analytics/summary').then(setData).catch(e=>setError(e.message))},[]);if(!data&&!error)return <Loader label="Analyzing operational data…"/>;return <><PageHeader eyebrow="Intelligence & trends" title="Crime analytics" subtitle="Explore synthetic incident patterns across category, time, location and case status."/>{error&&<Alert>{error}</Alert>}{data&&<><div className="metrics-grid"><MetricCard icon={ClipboardList} label="Total reports" value={data.totalReports} tone="blue"/><MetricCard icon={Activity} label="Under investigation" value={data.underInvestigation} tone="purple"/><MetricCard icon={CheckCircle2} label="Resolved" value={data.resolved} tone="green"/><MetricCard icon={ShieldAlert} label="High priority" value={data.highPriority} tone="red"/></div><div className="analytics-grid"><Chart title="Reports by category" eyebrow="Incident profile" className="chart-wide"><ResponsiveContainer width="100%" height={320}><BarChart data={data.categories} layout="vertical" margin={{left:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={90} tick={{fontSize:12}}/><Tooltip/><Bar dataKey="value" radius={[0,6,6,0]}>{data.categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></Chart><Chart title="Status distribution" eyebrow="Workflow health"><ResponsiveContainer width="100%" height={320}><PieChart><Pie data={data.statuses} dataKey="value" nameKey="name" outerRadius={105} innerRadius={58} paddingAngle={3}>{data.statuses.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend formatter={v=>v.replaceAll('_',' ')}/></PieChart></ResponsiveContainer></Chart><Chart title="Monthly reporting trend" eyebrow="12-month trajectory" className="chart-wide"><ResponsiveContainer width="100%" height={300}><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={3} dot={{r:4,fill:'#2563eb'}}/></LineChart></ResponsiveContainer></Chart><Chart title="Top locations" eyebrow="Geographic concentration"><div className="location-ranking">{data.locations.map((x,i)=><div key={x.name}><span><i>{i+1}</i><MapPin/> {x.name}</span><b>{x.value} reports</b><div style={{width:`${Math.max(12,(x.value/Math.max(...data.locations.map(y=>y.value)))*100)}%`}}/></div>)}</div></Chart></div></>}</>}
function Chart({title,eyebrow,className='',children}){return <section className={`panel analytics-card ${className}`}><div className="panel-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div></div>{children}</section>}

