import { Link } from 'react-router-dom'
import { Activity, ArrowRight, BarChart3, CheckCircle2, FileSearch, Fingerprint, LockKeyhole, MapPin, Radio, ShieldCheck, Siren, Users } from 'lucide-react'

export default function Landing() {
  return <div className="landing">
    <nav className="landing-nav"><Link className="brand" to="/"><span className="brand-mark"><Fingerprint /></span><span><strong>CrimeWatch</strong><small>Safer communities. Clearer response.</small></span></Link><div className="landing-links"><a href="#how">How it works</a><a href="#features">Capabilities</a><a href="#security">Security</a></div><div className="landing-actions"><Link className="button button-ghost" to="/login">Sign in</Link><Link className="button button-primary" to="/register">Report an incident <ArrowRight size={17} /></Link></div></nav>
    <main>
      <section className="hero"><div className="hero-copy"><div className="hero-kicker"><span className="live-dot" /> Community safety, connected in real time</div><h1>Every report deserves a <em>clear response.</em></h1><p>CrimeWatch connects citizens and law enforcement through secure incident reporting, visible case progress, and intelligence-led operations.</p><div className="hero-actions"><Link className="button button-primary button-large" to="/register"><Siren size={19} /> Report an incident</Link><Link className="button button-secondary button-large" to="/login">Access your workspace <ArrowRight size={18} /></Link></div><div className="trust-row"><span><CheckCircle2 /> Protected reporting</span><span><CheckCircle2 /> Live status tracking</span><span><CheckCircle2 /> Role-based access</span></div></div>
        <div className="hero-visual"><div className="map-grid" /><div className="radar"><span /><span /><span /><i /></div><div className="floating-card incident-card"><div className="float-icon red"><Siren /></div><div><small>NEW INCIDENT</small><strong>CR-2026-1030</strong><span>Central Ward · 2 min ago</span></div><b>HIGH</b></div><div className="floating-card response-card"><div className="float-icon green"><ShieldCheck /></div><div><small>RESPONSE UPDATE</small><strong>Officer assigned</strong><span>Unit CW-2031 responding</span></div></div><div className="coverage-card"><div><span>Operational visibility</span><strong>Live district overview</strong></div><div className="coverage-metrics"><div><b>30</b><span>demo reports</span></div><div><b>5</b><span>officers</span></div><div><b>6</b><span>status stages</span></div></div></div></div>
      </section>
      <section className="impact-strip"><span>One trusted operational picture</span><div><b>Secure</b><small>JWT-protected access</small></div><div><b>Accountable</b><small>Complete audit history</small></div><div><b>Responsive</b><small>End-to-end case timeline</small></div><div><b>Insightful</b><small>Actionable crime analytics</small></div></section>
      <section className="section how" id="how"><div className="section-heading"><span className="eyebrow">A transparent response journey</span><h2>From first report to final resolution</h2><p>Every participant sees the information and actions relevant to their role.</p></div><div className="step-grid"><Step n="01" icon={Siren} title="Report securely" text="Submit complete incident details, location, witness information and supporting evidence." /><Step n="02" icon={FileSearch} title="Review & assign" text="Administrators validate incoming reports, set priority and assign the right officer." /><Step n="03" icon={Radio} title="Investigate" text="Officers record investigation notes, evidence updates and accountable status changes." /><Step n="04" icon={CheckCircle2} title="Resolve visibly" text="Citizens receive notifications and follow the complete, timestamped case journey." /></div></section>
      <section className="section feature-section" id="features"><div className="section-heading left"><span className="eyebrow">Built for real operations</span><h2>Clarity for citizens.<br />Control for response teams.</h2></div><div className="feature-grid"><Feature icon={MapPin} title="Location intelligence" text="Find patterns across cities and areas through focused location analysis." /><Feature icon={Activity} title="Live case workflow" text="A governed six-stage lifecycle keeps every case moving visibly." /><Feature icon={BarChart3} title="Operational analytics" text="Understand categories, trends, priorities and resolution performance." /><Feature icon={Users} title="Role-aware workspaces" text="Purpose-built experiences for citizens, officers and administrators." /><Feature icon={LockKeyhole} title="Security by design" text="Hashed passwords, short-lived JWTs and server-side authorization." /><Feature icon={FileSearch} title="Complete audit trail" text="Important logins and case actions are captured for accountability." /></div></section>
      <section className="security-banner" id="security"><div><ShieldCheck size={42} /><span><b>Responsible demonstration system</b><p>All included records are synthetic. CrimeWatch never ships real personal or crime data.</p></span></div><Link className="button button-light" to="/login">Open demo workspace <ArrowRight size={17} /></Link></section>
    </main>
    <footer><div className="brand"><span className="brand-mark"><Fingerprint /></span><span><strong>CrimeWatch</strong><small>Real-Time Crime Report Management System</small></span></div><p>Built as a full DevOps laboratory system · Git · Jenkins · Docker · Ansible</p></footer>
  </div>
}

function Step({ n, icon: Icon, title, text }) { return <article className="step-card"><span className="step-number">{n}</span><div className="step-icon"><Icon /></div><h3>{title}</h3><p>{text}</p></article> }
function Feature({ icon: Icon, title, text }) { return <article className="feature-card"><Icon /><h3>{title}</h3><p>{text}</p></article> }

