import { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { ArrowLeft, CalendarDays, Check, ClipboardEdit, Clock3, FileText, FileUp, MapPin, MessageSquarePlus, ShieldCheck, UserRound, Users } from 'lucide-react'
import { api, formatDate, formatStatus } from '../api'
import { useAuth } from '../auth'
import { Alert, Loader, Modal, PageHeader, PriorityBadge, StatusBadge } from '../components/Ui'

const stages=['SUBMITTED','UNDER_REVIEW','ASSIGNED','UNDER_INVESTIGATION','RESOLVED','CLOSED']
export default function ReportDetail(){
  const {id}=useParams(),{user}=useAuth(),location=useLocation();const [report,setReport]=useState(null),[error,setError]=useState(''),[success,setSuccess]=useState(location.state?.created?'Report submitted successfully. Your tracking ID is ready.':''),[modal,setModal]=useState(''),[officers,setOfficers]=useState([])
  const load=()=>api(`/reports/${id}`).then(setReport).catch(e=>setError(e.message));useEffect(load,[id]);useEffect(()=>{if(user.role==='ADMIN')api('/admin/officers').then(setOfficers).catch(()=>{})},[user.role])
  const action=async(path,body,message)=>{try{setError('');const result=await api(path,{method:'PUT',body:JSON.stringify(body)});setReport(result);setModal('');setSuccess(message)}catch(e){setError(e.message)}}
  const note=async value=>{try{await api(`/reports/${id}/notes`,{method:'POST',body:JSON.stringify({note:value,internalOnly:true})});setModal('');setSuccess('Investigation note added.');load()}catch(e){setError(e.message)}}
  const upload=async file=>{try{const data=new FormData();data.append('file',file);await api(`/reports/${id}/evidence`,{method:'POST',body:data});setSuccess('Evidence uploaded securely.');load()}catch(e){setError(e.message)}}
  if(!report&&!error)return <Loader label="Opening secure case record…"/>;if(!report)return <Alert>{error}</Alert>;const index=stages.indexOf(report.status)
  return <><Link className="back-link app-back" to="/app/reports"><ArrowLeft/> Back to reports</Link><PageHeader eyebrow={`${report.category.name} · ${report.publicId}`} title={report.title} subtitle={`Reported ${formatDate(report.createdAt)} · Last updated ${formatDate(report.updatedAt)}`} action={<div className="detail-badges"><PriorityBadge value={report.priority}/><StatusBadge value={report.status}/></div>}/>{error&&<Alert onClose={()=>setError('')}>{error}</Alert>}{success&&<Alert type="success" onClose={()=>setSuccess('')}>{success}</Alert>}
    <div className="case-layout"><div className="case-main"><section className="panel case-overview"><div className="panel-head"><div><span className="eyebrow">Case summary</span><h2>Incident overview</h2></div></div><p className="case-description">{report.description}</p><div className="detail-grid"><Detail icon={CalendarDays} label="Date & time" value={`${formatDate(report.incidentDate)} · ${report.incidentTime?.slice(0,5)}`}/><Detail icon={MapPin} label="Location" value={`${report.location}, ${report.area||''} ${report.city}`}/><Detail icon={UserRound} label="Reported by" value={report.reporter.fullName}/><Detail icon={ShieldCheck} label="Assigned officer" value={report.assignedOfficer?.fullName||'Awaiting assignment'}/></div></section>
      <section className="panel timeline-panel"><div className="panel-head"><div><span className="eyebrow">Accountable workflow</span><h2>Case timeline</h2></div></div><div className="case-timeline">{stages.map((stage,i)=>{const event=report.history.find(h=>h.toStatus===stage);return <div className={`${i<index?'complete':i===index?'active':''}`} key={stage}><i>{i<=index?<Check/>:i+1}</i><div><b>{formatStatus(stage)}</b><span>{event?.comment||stageDescription(stage)}</span>{event&&<small>{formatDate(event.changedAt)} · {event.changedBy}</small>}</div></div>})}</div></section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">Investigation record</span><h2>Notes & evidence</h2></div>{user.role!=='CITIZEN'&&<button className="button button-secondary" onClick={()=>setModal('note')}><MessageSquarePlus/> Add note</button>}</div><div className="notes-list">{report.notes.length?report.notes.map(n=><article key={n.id}><span>{n.author.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{n.author}<small>{formatDate(n.createdAt)}</small></b><p>{n.note}</p>{n.internalOnly&&<em>Internal investigation note</em>}</div></article>):<p className="muted">No investigation notes have been recorded yet.</p>}</div><div className="evidence-block"><h3><FileText/> Evidence files</h3>{report.evidence.map(e=><div className="evidence-row" key={e.id}><FileText/><span><b>{e.fileName}</b><small>{e.contentType||'File'} · {Math.ceil((e.fileSize||0)/1024)} KB</small></span></div>)}<label className="mini-upload"><FileUp/> Add evidence<input type="file" onChange={e=>e.target.files[0]&&upload(e.target.files[0])}/></label></div></section>
    </div><aside className="case-aside"><section className="panel action-panel"><span className="eyebrow">Case controls</span><h2>Available actions</h2>{user.role==='ADMIN'&&<button onClick={()=>setModal('assign')}><Users/> Assign officer</button>}{user.role!=='CITIZEN'&&<button onClick={()=>setModal('status')}><ClipboardEdit/> Update status</button>}<label className="action-upload"><FileUp/> Add evidence<input type="file" onChange={e=>e.target.files[0]&&upload(e.target.files[0])}/></label></section><section className="panel metadata-panel"><span className="eyebrow">Additional details</span><Meta label="Suspect information" value={report.suspectInformation}/><Meta label="Witness information" value={report.witnessInformation}/><Meta label="Evidence description" value={report.evidenceDescription}/><Meta label="Additional remarks" value={report.additionalRemarks}/>{report.latitude&&<Meta label="Coordinates" value={`${report.latitude}, ${report.longitude}`}/>}</section></aside></div>
    {modal==='status'&&<StatusModal report={report} close={()=>setModal('')} submit={(status,comment)=>action(`/reports/${id}/status`,{status,comment},`Status changed to ${formatStatus(status)}.`)}/>} {modal==='assign'&&<AssignModal officers={officers} close={()=>setModal('')} submit={(officerId,priority)=>action(`/reports/${id}/assign`,{officerId:Number(officerId),priority},'Officer assigned successfully.')}/>} {modal==='note'&&<NoteModal close={()=>setModal('')} submit={note}/>}</>
}
function Detail({icon:Icon,label,value}){return <div className="detail-item"><Icon/><span><small>{label}</small><b>{value}</b></span></div>}
function Meta({label,value}){return <div className="meta-row"><small>{label}</small><p>{value||'Not provided'}</p></div>}
function stageDescription(s){return {SUBMITTED:'Report received',UNDER_REVIEW:'Pending completeness review',ASSIGNED:'Awaiting officer assignment',UNDER_INVESTIGATION:'Investigation pending',RESOLVED:'Outcome pending',CLOSED:'Formal closure pending'}[s]}
function StatusModal({report,close,submit}){const [status,setStatus]=useState(report.status),[comment,setComment]=useState('');return <Modal title="Update case status" onClose={close}><div className="modal-body"><label className="field"><span>New status</span><select value={status} onChange={e=>setStatus(e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Update note</span><textarea rows="4" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Explain this status change"/></label><div className="modal-actions"><button className="button button-ghost" onClick={close}>Cancel</button><button className="button button-primary" onClick={()=>submit(status,comment)}>Save status</button></div></div></Modal>}
function AssignModal({officers,close,submit}){const [officer,setOfficer]=useState(officers[0]?.id||''),[priority,setPriority]=useState('MEDIUM');return <Modal title="Assign investigating officer" onClose={close}><div className="modal-body"><label className="field"><span>Available officer</span><select value={officer} onChange={e=>setOfficer(e.target.value)}>{officers.map(o=><option key={o.id} value={o.id}>{o.fullName} · {o.badgeNumber} · {o.department}</option>)}</select></label><label className="field"><span>Case priority</span><select value={priority} onChange={e=>setPriority(e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(p=><option key={p}>{p}</option>)}</select></label><div className="modal-actions"><button className="button button-ghost" onClick={close}>Cancel</button><button className="button button-primary" disabled={!officer} onClick={()=>submit(officer,priority)}>Assign case</button></div></div></Modal>}
function NoteModal({close,submit}){const [note,setNote]=useState('');return <Modal title="Add investigation note" onClose={close}><div className="modal-body"><label className="field"><span>Internal case note</span><textarea rows="7" value={note} onChange={e=>setNote(e.target.value)} placeholder="Record observations, actions, or evidence updates…"/></label><p className="form-hint">This note is visible to authorized police and administrative users.</p><div className="modal-actions"><button className="button button-ghost" onClick={close}>Cancel</button><button className="button button-primary" disabled={note.length<3} onClick={()=>submit(note)}>Add note</button></div></div></Modal>}
